USE [master]
GO

/****** Object:  Database [SemanticKernelWebClient]    Script Date: 12/29/2025 3:59:47 PM ******/
CREATE DATABASE [SemanticKernelWebClient]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SemanticKernelWebClient', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\SemanticKernelWebClient.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SemanticKernelWebClient_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\SemanticKernelWebClient_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SemanticKernelWebClient].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SemanticKernelWebClient] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ARITHABORT OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SemanticKernelWebClient] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SemanticKernelWebClient] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SemanticKernelWebClient] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SemanticKernelWebClient] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET RECOVERY FULL 
GO

ALTER DATABASE [SemanticKernelWebClient] SET  MULTI_USER 
GO

ALTER DATABASE [SemanticKernelWebClient] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SemanticKernelWebClient] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SemanticKernelWebClient] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SemanticKernelWebClient] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SemanticKernelWebClient] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SemanticKernelWebClient] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [SemanticKernelWebClient] SET QUERY_STORE = ON
GO

ALTER DATABASE [SemanticKernelWebClient] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SemanticKernelWebClient] SET  READ_WRITE 
GO


